### ISSUE TITLE
Cortana “Ask me anything” box disabled in IOS

### ISSUE THREAD

**Issue by ramseen** [Microsoft/Cortana-Skills-Samples-Build-2017#1]
I have added my sample Bot to cortana. its working good in andriod device , when i ask like "ask sample bot" it will get connected to my bot . like wise I have been running my cortana skill set in andriod device , but in IPad or Iphone cortana when i ask like that , it get connect to bot and immediately the bottom textbox will be disabled , the box is grayed out, and I can't type into it .

Is there any unique specification for IOS cortana for connecting skill set ??

please help out .!!

**Comment by rbrundritt** [comment]
Please direct your question tot he [Cortana Skills forum](https://social.msdn.microsoft.com/Forums/en-us/home?forum=cortanaskillskit). This project is not actively monitored.
