### ISSUE TITLE
Cortana custom skill on Harmon Kardon Invoke

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/Cortana-Skills-Samples-Build-2017#4]
Bot Info

App ID: 984ede7e-bc35-4767-a19b-60a2d6c5e4be
SDK Platform: Node.js
SDK Version:
Active Channels: Cortana , Direct Line
Deployment Environment: Azure App Service

I have created a bot service on node.js and added Cortan channel. I am able to connect to custom skill in Cortana app in iOS device. Once connected its able to maintain the conversations correctly. 
Ex: All the steps in waterfall model with multiple dialogs works until I call endConversation(). 

Issue with Harmon Kardon Invoke is its not able to go through all functions of waterfall. As in intents with single dialog and single function woks fine with invoke but if I have waterfall of course with multiple functions then HK invoke will not recognize it.  

Ex:- https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-manage-conversation-flow

User says: hey cortana ask {invocation name} {utterance} 
then sometime  utterance is stripped. Also, utterance having single words like 'help' , 'hi' are working expected and skill gets killed after that. Each time we have to say hey cortana ask {invocation name} {utterance} 

I know HK invoke is new and there is very minimal info I could find on internet. Please let me know if my question is not clear.

**Comment by rbrundritt** [comment]
Please ask your question in the developer forums, this project is am archive of content from the Microsoft Build conference. Many of contributors to this project are not on the Cortana Skills kit team.

MSDN: https://social.msdn.microsoft.com/Forums/en-us/home?forum=cortanaskillskit
StackOverflow: http://stackoverflow.com/questions/tagged/cortana-skills-kit
